# Generated by Django 6.0.6 on 2026-06-19 03:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aisles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='markets.market')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Mahalle İsmi')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='İlçe')),
                ('address', models.TextField(blank=True, verbose_name='Tam Adres')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Tam konum')),
                ('delivery_radius_km', models.PositiveIntegerField(default=5, verbose_name='Teslimat Menzili (KM)')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='markets.market')),
            ],
        ),
        migrations.CreateModel(
            name='AislesBranchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available_in_branch', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.aisles')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Adı')),
                ('surname', models.CharField(max_length=50, verbose_name='Soyadı')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motosiklet'), ('car', 'Araba')], default='moto', max_length=10, verbose_name='Araç Tipi')),
                ('status', models.CharField(choices=[('offline', 'Çevrimdışı'), ('available', 'Müsait (Şubede Bekliyor)'), ('delivery', 'Dağıtımda / Siparişte')], default='offline', max_length=15, verbose_name='Durumu')),
                ('current_cart_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Şu Anki Sepet ID')),
                ('monthly_delivered_cart_ids', models.JSONField(blank=True, default=list, verbose_name="Bu Ay Teslim Edilen Sepet ID'leri")),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Anlık Konum')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='merchant.branch', verbose_name='Bağlı Olduğu Şube')),
            ],
            options={
                'verbose_name': 'Kurye',
                'verbose_name_plural': 'Kuryeler',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='product-images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField()),
                ('aisles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.aisles')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.branch')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='merchant.products')),
            ],
        ),
    ]
