# Generated by Django 6.0.6 on 2026-07-09 21:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Aisles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='markets.market')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Şube Adı')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='İlçe')),
                ('address', models.TextField(blank=True, verbose_name='Tam Adres')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Tam konum')),
                ('delivery_radius_km', models.PositiveIntegerField(default=5, verbose_name='Teslimat Menzili (KM)')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='markets.market')),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Adı')),
                ('surname', models.CharField(max_length=50, verbose_name='Soyadı')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motosiklet'), ('car', 'Araba')], default='motorcycle', max_length=10, verbose_name='Araç Tipi')),
                ('status', models.CharField(choices=[('offline', 'Çevrimdışı'), ('available', 'Müsait (Şubede Bekliyor)'), ('delivery', 'Dağıtımda / Siparişte')], default='offline', max_length=15, verbose_name='Durumu')),
                ('monthly_delivery_count', models.PositiveIntegerField(default=0, verbose_name='Bu Ayki Teslimat Sayısı')),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Anlık Konum')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='merchant.branch', verbose_name='Bağlı Olduğu Şube')),
            ],
            options={
                'verbose_name': 'Kurye',
                'verbose_name_plural': 'Kuryeler',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Takip Numarası')),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'Kapıda Nakit'), ('card_on_delivery', 'Kapıda Kredi Kartı'), ('online_credit_card', 'Online Kredi Kartı')], default='online_credit_card', max_length=30, verbose_name='Ödeme Yöntemi')),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('preparing', 'Hazırlanıyor'), ('ready', 'Paket Hazır / Kurye Bekliyor'), ('on_the_way', 'Kurye Dağıtımda'), ('delivered', 'Teslim Edildi'), ('canceled', 'İptal Edildi')], default='pending', max_length=15, verbose_name='Paket Durumu')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Paket Tutarı')),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=255, verbose_name='Müşteri Adı Soyadı (Snapshot)')),
                ('customer_phone_snapshot', models.CharField(blank=True, max_length=20, verbose_name='Müşteri Telefonu (Snapshot)')),
                ('delivery_address', models.TextField(verbose_name='Teslimat Adresi (Snapshot)')),
                ('package_index', models.JSONField(blank=True, default=list, verbose_name='Paketin İçeriği')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Paket Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Durum Güncellemesi')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Yola Çıkış Zamanı')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Edilme Zamanı')),
                ('address_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address', verbose_name='Kayıtlı Adres Referansı')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='merchant.branch', verbose_name='Çıkış Şubesi')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='merchant.courier', verbose_name='Kurye')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='account.user', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Paket',
                'verbose_name_plural': 'Paketler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='product-images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('aisles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.aisles')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='markets.market')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('ailes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='merchant.aisles')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='merchant.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='merchant.products')),
            ],
        ),
        migrations.CreateModel(
            name='AislesBranchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available_in_branch', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.aisles')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.branch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('branch', 'category'), name='unique_branch_category_mapping')],
            },
        ),
    ]
