# Generated by Django 6.0.6 on 2026-06-21 02:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Takip Numarası')),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('preparing', 'Hazırlanıyor'), ('ready', 'Paket Hazır / Kurye Bekliyor'), ('on_the_way', 'Kurye Dağıtımda'), ('delivered', 'Teslim Edildi'), ('canceled', 'İptal Edildi')], default='pending', max_length=15, verbose_name='Paket Durumu')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Paket Tutarı')),
                ('delivery_address', models.TextField(verbose_name='Teslimat Adresi (Snapshot)')),
                ('package_index', models.JSONField(verbose_name='Paketin İçeriği')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Paket Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Durum Güncellemesi')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Yola Çıkış Zamanı')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Edilme Zamanı')),
                ('address_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address', verbose_name='Kayıtlı Adres Referansı')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='merchant.branch', verbose_name='Çıkış Şubesi')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='merchant.courier', verbose_name='Kurye')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='account.user', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Paket',
                'verbose_name_plural': 'Paketler',
                'ordering': ['-created_at'],
            },
        ),
    ]
