# Generated by Django 6.0.6 on 2026-07-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aislesbranchsettings',
            name='unique_branch_category_mapping',
        ),
        migrations.DeleteModel(
            name='AislesBranchSettings',
        ),
    ]
