# Generated by Django 6.0.6 on 2026-07-19 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        ('merchant', '0002_remove_aislesbranchsettings_unique_branch_category_mapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='aisles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='merchant.aisles'),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('discount_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='İndirim Oranı (%)')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Kampanya Başlangıç Tarihi')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='Kampanya Bitiş Tarihi')),
                ('is_active', models.BooleanField(default=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Campaign', to='markets.market')),
            ],
        ),
    ]
