# Generated by Django 6.0.6 on 2026-06-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='vehicle_type',
            field=models.CharField(choices=[('motorcycle', 'Motosiklet'), ('car', 'Araba')], default='motorcycle', max_length=10, verbose_name='Araç Tipi'),
        ),
    ]
