# Generated by Django 6.0.6 on 2026-07-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_alter_products_aisles_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='use_count',
            field=models.IntegerField(default=0),
        ),
    ]
