# Generated by Django 6.0.6 on 2026-06-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_alter_courier_vehicle_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='monthly_delivered_cart_ids',
        ),
        migrations.AddField(
            model_name='courier',
            name='monthly_delivery_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Bu Ayki Teslimat Sayısı'),
        ),
    ]
