# Generated by Django 6.0.6 on 2026-07-27 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        ('merchant', '0004_campaign_use_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={},
        ),
        migrations.RemoveField(
            model_name='package',
            name='address_reference',
        ),
        migrations.AddField(
            model_name='package',
            name='address_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Addres id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='markets.market', verbose_name='Market'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='delivery_address',
            field=models.TextField(verbose_name='Teslimat Adresi'),
        ),
    ]
