# Generated by Django 6.0.5 on 2026-06-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=128)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('login_dates', models.JSONField(blank=True, default=list)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
