# Generated by Django 6.0.6 on 2026-07-27 02:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=1, srid=4326),
            preserve_default=False,
        ),
    ]
