# Generated by Django 6.0.6 on 2026-06-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
