# Generated by Django 6.0.6 on 2026-06-13 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_address_usercard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCard',
            new_name='Card',
        ),
    ]
