# Generated by Django 6.0.6 on 2026-06-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_usercard_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='cvv',
            new_name='card_cvv',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='name_on_card',
            new_name='card_holder',
        ),
    ]
