# Generated by Django 6.0.6 on 2026-06-13 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_cvv_card_card_cvv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='full_address',
            new_name='address_detail',
        ),
    ]
