# Generated by Django 6.0.6 on 2026-06-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_full_address_address_address_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
    ]
