# Generated by Django 6.0.6 on 2026-06-19 03:36

import datetime
import django.db.models.deletion
import markets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Market Adı')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL Uzantısı)')),
                ('min_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Minimum Sepet Tutarı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=markets.models.market_logo_path, verbose_name='Market Logosu')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=markets.models.market_banner_path, verbose_name='Market Banner Resmi')),
                ('status', models.BooleanField(default=True, verbose_name='Sistemde Aktif mi?')),
                ('home', models.BooleanField(default=False, verbose_name='Home pagede gözüküyormu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Marketler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketBusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Gün')),
                ('open_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Açılış Saati')),
                ('close_time', models.TimeField(default=datetime.time(22, 0), verbose_name='Kapanış Saati')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Bugün Tamamen Kapalı mı?')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='markets.market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Çalışma Saati',
                'verbose_name_plural': 'Çalışma Saatleri',
                'ordering': ['day'],
                'unique_together': {('market', 'day')},
            },
        ),
    ]
