# Generated by Django 6.0.6 on 2026-06-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Market Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Market Açıklaması')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='Market Konumu')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug (URL)')),
                ('min_price', models.IntegerField(default=0, verbose_name='Minimum Fiyat')),
                ('status', models.BooleanField(default=True, verbose_name='Durum (Aktif/Pasif)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='market_logos/', verbose_name='Market Logosu')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='market_banners/', verbose_name='Market Afişi')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Marketler',
            },
        ),
    ]
