# Generated by Django 6.0.6 on 2026-06-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='description',
        ),
    ]
