# Generated by Django 6.0.6 on 2026-06-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_remove_market_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL)'),
        ),
    ]
