# Generated by Django 6.0.6 on 2026-06-07 13:14

import markets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_alter_market_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=markets.models.market_banner_path, verbose_name='Market Afişi'),
        ),
        migrations.AlterField(
            model_name='market',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=markets.models.market_logo_path, verbose_name='Market Logosu'),
        ),
    ]
