# Generated by Django 6.0.6 on 2026-06-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_alter_market_banner_alter_market_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Durum (Aktif/Kapalı)'),
        ),
    ]
