# Generated by Django 6.0.6 on 2026-06-07 13:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_alter_market_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Sistemde Aktif mi?'),
        ),
        migrations.CreateModel(
            name='MarketBusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Gün')),
                ('open_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Açılış Saati')),
                ('close_time', models.TimeField(default=datetime.time(22, 0), verbose_name='Kapanış Saati')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Bugün Tamamen Kapalı mı?')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='markets.market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Çalışma Saati',
                'verbose_name_plural': 'Çalışma Saatleri',
                'unique_together': {('market', 'day')},
            },
        ),
    ]
