# Generated by Django 6.0.6 on 2026-06-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_alter_market_status_marketbusinesshour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Home pagede gözüküyormu'),
        ),
    ]
