# Generated by Django 6.0.6 on 2026-06-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_alter_market_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='home',
            field=models.BooleanField(default=False, verbose_name='Home pagede gözüküyormu'),
        ),
        migrations.AlterField(
            model_name='market',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Sistemde Aktif mi?'),
        ),
    ]
