# Generated by Django 4.2 on 2026-06-12 23:42

from django.db import migrations, models
import django.utils.timezone
import markets.models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_market_home_alter_market_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['-created_at'], 'verbose_name': 'Market', 'verbose_name_plural': 'Marketler'},
        ),
        migrations.AlterModelOptions(
            name='marketbusinesshour',
            options={'ordering': ['day'], 'verbose_name': 'Çalışma Saati', 'verbose_name_plural': 'Çalışma Saatleri'},
        ),
        migrations.RemoveField(
            model_name='market',
            name='home',
        ),
        migrations.AddField(
            model_name='market',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Kayıt Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='market',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=markets.models.market_banner_path, verbose_name='Market Banner Resmi'),
        ),
        migrations.AlterField(
            model_name='market',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Minimum Sepet Tutarı'),
        ),
        migrations.AlterField(
            model_name='market',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL Uzantısı)'),
        ),
    ]
