# Generated by Django 6.0.6 on 2026-06-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0009_alter_market_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='home',
            field=models.BooleanField(default=False, verbose_name='Home pagede gözüküyormu'),
        ),
    ]
